#!/bin/sh
nm="UniStore"
vs="r1"
unistoreversion="""
        \e[1;42m $nm \e[0m\e[100m version $vs \e[0m
        \e[100m Created in 08-05-2019 (a epoch with no Internet and my own mom un-consciently attacking) by Daniell Mesquita \e[0m
"""

# todo: tell about Floflis Packager when trying to publish/send update
# todo: orange color for UniStore
# todo: icon, send notification about installs

if [ "$1" = "" ]; then
   echo "$unistoreversion"
   echo "Type 'unistore --help' (without quotes) to see a list of available commands."
fi

if [ "$1" = "--help" ] || [ "$1" = "-h" ]; then
   echo "        \e[1;42m $nm $vs \e[0m"
   echo "Use these commands after/together with 'unistore' command."
   echo "Available commands:"
   echo "Information:"
   echo "   --help, -h                  Shows all available commands"
   echo "   --version, -v               Shows the version of $nm"
fi

# Install: dat clone
# Update: dat pull

if [ "$1" = "--version" ] || [ "$1" = "-v" ]; then
   echo "$unistoreversion"
fi
